[env]
_.file = ".env"

[tasks.build]
alias = "b"
run = "go build -o server"

[tasks.local-deploy]
alias = "ld"
depends = ["build"]
run = "cp ./server ~/.local/bin/tudidi_mcp"

[tasks.test]
alias = "t"
run = "go test ./..."

[tasks.lint]
run = "go vet ./..."

[tasks.fmt]
alias = "f"
run = "go fmt ./..."
